variable "aws_creds_file" {}
variable "tag_name_prefix" {}
variable "region" {}
variable "aws_key_name" {}
variable "availability_zone1" {}
variable "vpc_cidr_block" {}
variable "subnet1_block" {}
variable "subnet1_ip_gw" {}
variable "subnet1_ip_fg1" {}
variable "subnet2_block" {}
variable "subnet2_ip_gw" {}
variable "subnet2_ip_fg1" {}
variable "subnet3_block" {}
variable "subnet3_ip_fg1" {}
variable "fg1_license" {}
variable "instance_type" {}
variable "sslpassword" {}